# This is a basic workflow that is manually triggered

name: Generate pages.json

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  push:
    branches:
    - main

jobs:
  generate_pages_json:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install pipenv
      run: |
        python -m pip install --upgrade pip
        pip install pipenv

    - name: Install dependencies
      run: |
        pipenv install --deploy --dev

    - name: Debug environment
      run: |
        echo "Python version:"
        python --version
        echo "Pipenv version:"
        pipenv --version
        echo "Pip list:"
        pipenv run pip list
        echo "Current directory:"
        pwd
        echo "Directory contents:"
        ls -la

    - name: Generate pages.json
      run: |
      pipenv shell
      python scripts/generate-pages-json.py

    - name: Commit and push pages.json if changed
      run: |
        git config --global user.name 'GitHub Actions'
        git config --global user.email 'actions@github.com'
        git add -A
        git diff --quiet && git diff --staged --quiet || (git commit -m "automatically update pages.json" && git push)
